COMMON: &common
  HOST: localhost
  PORT: 3000
  # defines the valid API key for the application
  API_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
  DEBUG: False
  TESTING: False
  LOGGING: True
  LOG_FILE_PATH: 'logs'
  LOG_FILE: 'cbibs_api.log'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'postgres://localhost/ncbo_dev'

PRODUCTION: &production
  <<: *common
  DEBUG: False
  SQLALCHEMY_DATABASE_URI: 'postgres://localhost/ncbo_dev'
